/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
	public int fib(int n) {
		if (n <= 1) {
			return n;
		}
		int fib = 1;
		int prev = 1;
		for (int i = 2; i < n; ++i) {
			int tmp = fib;
			fib += prev;
			prev = tmp;
		}
		return fib;
	}
}
